name: build

on:
  workflow_dispatch:
  push:
    branches: [ '[0-9]+.[0-9]' ]
  pull_request:
    branches: [ '[0-9]+.[0-9]' ]

permissions:
  contents: read

jobs:
  static-analysis:
    name: "Static analysis (PHP ${{ matrix.php }})"

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2', '8.3', '8.4', '8.5' ]

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo_mysql, pdo_pgsql

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare composer cache
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Require event store dev version
        # TODO point back to "neos/eventstore:2.0.x-dev as 2.0" once task/improve-tests is merged
        run: composer require --no-update --no-interaction "neos/eventstore:dev-task/improve-tests as 2.0"

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPStan
        run: composer run test:phpstan

      - name: Run CS
        run: composer run test:cs

  #    - name: Validate composer.json and composer.lock
  #      run: composer validate --strict

  tests:
    name: "Tests (PHP ${{ matrix.php }}, ${{ matrix.db.image }})"

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2', '8.3', '8.4', '8.5' ]
        db:
          - { engine: mysql, image: 'mariadb:10.6', port: 3306, options: '--health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3' }
          - { engine: pgsql, image: 'postgres:14-alpine', port: 5432, options: '--health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3' }
        include:
          # SQLite engines.
          - { php: '8.4', db: { engine: sqlite, image: null } }
          # MySQL engines.
          - { php: '8.4', db: { engine: mysql, image: 'mysql:8.0', port: 3306, options: '--health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3' } }
          - { php: '8.4', db: { engine: mysql, image: 'mysql:8.4', port: 3306, options: '--health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3' } }
          # Bleeding-edge engines.
          - { php: '8.5', db: { engine: mysql, image: 'mariadb:latest', port: 3306, options: '--health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3' } }
          - { php: '8.5', db: { engine: mysql, image: 'mysql:latest', port: 3306, options: '--health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3' } }
          - { php: '8.5', db: { engine: pgsql, image: 'postgres:latest', port: 5432, options: '--health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3' } }

    env:
      DB_DSN: |-
        ${{ case(
          matrix.db.engine == 'sqlite',
            'sqlite:///events_test.sqlite',
          matrix.db.engine == 'mysql',
            format('pdo-mysql://neos:neos@127.0.0.1:{0}/eventstore', matrix.db.port),
          matrix.db.engine == 'pgsql',
            format('pdo-pgsql://neos:neos@127.0.0.1:{0}/eventstore', matrix.db.port),
          ''
        ) }}

    runs-on: ubuntu-latest

    services:
      database:
        image: ${{ matrix.db.image }}
        env:
          MYSQL_USER: neos
          MYSQL_PASSWORD: neos
          MYSQL_DATABASE: eventstore
          MYSQL_ROOT_PASSWORD: neos
          POSTGRES_USER: neos
          POSTGRES_PASSWORD: neos
          POSTGRES_DB: eventstore
        ports:
          - "${{ matrix.db.port }}:${{ matrix.db.port }}"
        options: ${{ matrix.db.options }}

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: pdo_mysql, pdo_pgsql

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare composer cache
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Require event store dev version
      # TODO point back to "neos/eventstore:2.0.x-dev as 2.0" once task/improve-tests is merged
      run: composer require --no-update --no-interaction "neos/eventstore:dev-task/improve-tests as 2.0"

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Integration Tests
      run: composer run test:integration

    - name: Run Consistency Tests
      id: consistencytests
      run: composer run test:consistency -v
      timeout-minutes: 30
      continue-on-error: true

    - name: Fail pipeline if Consistency Tests broke
      if: steps.consistencytests.outcome != 'success'
      shell: bash
      run: |
        echo '${{ toJSON(steps) }}'
        echo "\n\nDumping last 100 events\n\n"
        ${{ case(
          matrix.db.engine == 'mysql',
            format('mysql -u neos -pneos -h 127.0.0.1 -P {0} eventstore --table < <(echo "SELECT * FROM events_test ORDER BY sequenceNumber DESC LIMIT 100")', matrix.db.port),
          'echo "Not implemented"'
        ) }}
        exit 1
